In [207]:
import pandas as pds
import numpy as np
N=100000
assig = pds.read_csv('train_2011_2012_2013.csv',delimiter=';',usecols=['ASS_ASSIGNMENT'], nrows=N).values.tolist()
date = pds.read_csv('train_2011_2012_2013.csv',delimiter=';',usecols=['DATE'], nrows=N).values.tolist()
calls = pds.read_csv('train_2011_2012_2013.csv',delimiter=';',usecols=['CSPL_RECEIVED_CALLS'], nrows=N).values.tolist()

In [208]:
def uniq(input):
    output = []
    for x in input:
        if x not in output:
            output.append(x)
    return output

In [209]:
uniq(assig)

[['Téléphonie'],
 ['RTC'],
 ['Gestion Renault'],
 ['Nuit'],
 ['Gestion - Accueil Telephonique'],
 ['Regulation Medicale'],
 ['Services'],
 ['Tech. Total'],
 ['Gestion Relation Clienteles'],
 ['Crises'],
 ['Japon'],
 ['Médical'],
 ['Gestion Assurances'],
 ['Domicile'],
 ['Gestion'],
 ['SAP'],
 ['RENAULT'],
 ['Gestion Amex'],
 ['Tech. Inter'],
 ['Gestion Clients'],
 ['Manager'],
 ['Tech. Axa'],
 ['CAT'],
 ['Gestion DZ'],
 ['Mécanicien'],
 ['CMS'],
 ['Prestataires'],
 ['Evenements']]

In [210]:
calls_ar = np.reshape(np.asarray(calls), N)
date_ar = np.reshape(np.asarray(date), N)

In [211]:
feature = 'Téléphonie'
position = []
for i, item in enumerate(assig):
    if item[0] == feature:
        position.append(i)

In [212]:
calls_f = calls_ar[position]
date_f = date_ar[position]

In [213]:
date_fu = np.asarray(uniq(date_f))
sz_new = date_fu.shape[0]
calls_fu = np.zeros(sz_new)
k=0
for i in range(0, sz_new):
    date = date_fu[i]
    while(date_f[k] == date):
        calls_fu[i]+=calls_f[k]
        k+=1

In [214]:
sz = calls_fu.shape[0]
day_fu = np.zeros(sz)
time_fu = np.zeros(sz)
print(sz)

1543


In [215]:
import datetime as dt
import re
for i in range(0,sz):
    s = date_fu[i]
    s = re.findall('\d+', s)
    day_fu[i] = dt.datetime(int(s[0]), int(s[1]), int(s[2])).weekday()
    time_fu[i] = int(s[3])+0.5*np.sign(int(s[4]))

In [216]:
calls_fu

array([ 1.,  0.,  0., ...,  0.,  0.,  0.])

In [217]:
day_fu

array([ 6.,  0.,  5., ...,  6.,  6.,  0.])

In [218]:
time_fu

array([ 1.5,  1.5,  0. , ...,  7. ,  6.5,  6.5])